{{- if (.Values.deployment.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nriKubernetes.labels" . | nindent 4 }}
  name: {{ include "nriKubernetes.deployment.fullname" . }}
  {{- $legacyAnnotation:= fromYaml (include "newrelic.compatibility.annotations" .) -}}
  {{- with  include "newrelic.compatibility.valueWithFallback" (dict "legacy" $legacyAnnotation "supported" .Values.deployment.annotations )}}
  annotations: {{ . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "newrelic.common.labels.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: deployment
  template:
    metadata:
      annotations:
        checksum/agent-config: {{ include (print $.Template.BasePath "/deployment/agent-configmap.yaml") . | sha256sum }}
        {{- if include "newrelic.common.license.secret" . }}{{- /* If the is secret to template */}}
        checksum/license-secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        checksum/integrations_config: {{ include (print $.Template.BasePath "/deployment/integrations-configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nriKubernetes.labels.podLabels" . | nindent 8 }}
        app.kubernetes.io/component: deployment
    spec:
      {{- with include "newrelic.common.images.renderPullSecrets" ( dict "pullSecrets" (list .Values.images.pullSecrets) "context" .) }}
      imagePullSecrets:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with include "newrelic.common.dnsConfig" . }}
      dnsConfig:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with include "newrelic.common.priorityClassName" . }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with include "newrelic.common.securityContext.pod" . }}
      securityContext:
        {{- . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "newrelic.common.serviceAccount.name" . }}
      hostNetwork: {{ include "newrelic.common.hostNetwork.value" . }}
      {{- if include "nriKubernetes.controlPlane.hostNetwork" . }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}

      {{- if .Values.deployment.initContainers }}
      initContainers: {{- tpl (.Values.deployment.initContainers | toYaml) . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          image: {{ include "newrelic.common.images.image" ( dict "imageRoot" .Values.images.agent "context" .) }}
          args: [ "newrelic-infra" ]
          imagePullPolicy: {{ .Values.images.agent.pullPolicy }}
          {{- with include "nriKubernetes.deployment.securityContext.agentContainer" . | fromYaml }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ get (fromYaml (include "nriKubernetes.deployment.agentConfig" .)) "http_server_port" }}
          env:
            - name: NRIA_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "newrelic.common.license.secretName" . }}
                  key: {{ include "newrelic.common.license.secretKeyName" . }}

            - name: "NRIA_OVERRIDE_HOSTNAME_SHORT"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "spec.nodeName"

            - name: "NRIA_OVERRIDE_HOSTNAME"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "spec.nodeName"

            {{- if not (include "newrelic.common.privileged" .) }}
            # Override NRIA_OVERRIDE_HOST_ROOT to empty if unprivileged. This must be done as an env var as the
            # `k8s-events-forwarder` and `infrastructure-bundle` images ship this very same env var set to /host.
            - name: "NRIA_OVERRIDE_HOST_ROOT"
              value: ""
            {{- end }}

            - name: "NRI_KUBERNETES_NODE_NAME"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "spec.nodeName"

            {{- if .Values.useNodeNameAsDisplayName }}
            - name: "NRIA_DISPLAY_NAME"
            {{- if .Values.prefixDisplayNameWithCluster }}
              value: "{{ include "newrelic.common.cluster" . }}:$(NRI_KUBERNETES_NODE_NAME)"
            {{- else }}
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "spec.nodeName"
            {{- end }}
            {{- end }}

            {{- /* Needed to populate clustername in integration metrics */}}
            - name: "CLUSTER_NAME"
              value: {{ include "newrelic.common.cluster" . }}
            - name: "NRIA_PASSTHROUGH_ENVIRONMENT"
              value: "CLUSTER_NAME"

            {{- /* Needed for autodiscovery since hostNetwork=false */}}
            - name: "NRIA_HOST"
              valueFrom:
                fieldRef:
                  apiVersion: "v1"
                  fieldPath: "status.hostIP"

            {{- with .Values.deployment.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.deployment.extraEnvFrom }}
          envFrom: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/newrelic-infra.yml
              subPath: newrelic-infra.yml
            - name: nri-integrations-cfg-volume
              mountPath: /etc/newrelic-infra/integrations.d/
            {{- if include "newrelic.common.privileged" . }}
            - name: dev
              mountPath: /dev
            - name: host-docker-socket
              mountPath: /var/run/docker.sock
            - name: log
              mountPath: /var/log
            - name: host-volume
              mountPath: /host
              readOnly: true
            {{- end }}
            - mountPath: /var/db/newrelic-infra/data
              name: agent-tmpfs-data
            - mountPath: /var/db/newrelic-infra/user_data
              name: agent-tmpfs-user-data
            - mountPath: /tmp
              name: agent-tmpfs-tmp
            {{- with .Values.deployment.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.deployment.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if include "newrelic.common.privileged" . }}
        - name: dev
          hostPath:
            path: /dev
        - name: host-docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: log
          hostPath:
            path: /var/log
        - name: host-volume
          hostPath:
            path: /
        {{- end }}
        - name: agent-tmpfs-data
          emptyDir: {}
        - name: agent-tmpfs-user-data
          emptyDir: {}
        - name: agent-tmpfs-tmp
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "nriKubernetes.deployment.fullname.agent" . }}
            items:
              - key: newrelic-infra.yml
                path: newrelic-infra.yml
        - name: nri-integrations-cfg-volume
          configMap:
            name: {{ include "nriKubernetes.deployment.fullname.integrations" . }}
        {{- with .Values.deployment.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with include "nriKubernetes.deployment.affinity" . }}
      affinity:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with include "nriKubernetes.deployment.tolerations" . }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector | default (fromYaml (include "newrelic.common.nodeSelector" .)) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
{{- end }}
